Models
best-cat-hustlers/cs446-project pull request #1
Opened 2019-06-19 18:58 UTC by KIsForCookie

Initial implementation of Model Classes. More things will be added/removed/refactored as necessary.

BoardGame: Class for interacting with puzzle and players. Can generate puzzles, fill in squares, and find the winner for each game.

Player: Class to represent players. Holds id and current score.

PuzzleGenerator: Class that generates sudoku puzzles and solutions.

Puzzle: Struct to pair puzzles and solutions.

2019-06-19 19:03 UTC, KIsForCookie commented
This was also done at 5 in the morning so I'm sure there's things I missed.

2019-06-19 21:40 UTC, xjchong requested changes
I'm wondering if maybe this PR is still a WIP. We need the models, but it looks like the puzzle generation still has a lot of TODOs in it, etc. Maybe it would have been better to have pushed just the model additions first, and then the puzzle generation could come after it?

2019-06-19 21:40 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/BoardGame.java
> +            // TODO: What if score is tied?
Should we return null values?

2019-06-19 21:40 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/PuzzleGenerator.java
> +// TODO: delete this import
Does this need to be deleted then? I'm not sure if you intend to keep the logging messages inside, but if you do maybe you can make a flag for them instead.

2019-06-19 21:40 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/PuzzleGenerator.java
> +    private boolean allowed(int[][] arr, int row, int col, int val)
Just a note here, is this your convention for boolean values? I would expect something like `isAllowed`.

2019-06-19 21:40 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/PuzzleGenerator.java
> +}
Should there be a newline at the end of the file?

2019-06-19 21:57 UTC, KIsForCookie commented on app/src/main/java/com/bestCatHustlers/sukodublitz/BoardGame.java
> +            // TODO: What if score is tied?
I think that returning null is a good way to signal that there is no winner i.e. the game is not over yet.
In the case where the score is tied, we could return null but we would then have to check if it is null because the game is not over yet or if there's ties.

2019-06-19 21:58 UTC, KIsForCookie commented on app/src/main/java/com/bestCatHustlers/sukodublitz/PuzzleGenerator.java
> +// TODO: delete this import
I was planning on taking them out when everything was done but since we wanted the basic model to be merged I just left it in so I can continue working on it afterwards.

2019-06-19 21:59 UTC, KIsForCookie commented on app/src/main/java/com/bestCatHustlers/sukodublitz/PuzzleGenerator.java
> +    private boolean allowed(int[][] arr, int row, int col, int val)
Just my convention. Anyways it's a private method so nobody should be interfacing with it.

2019-06-19 22:00 UTC, KIsForCookie commented on app/src/main/java/com/bestCatHustlers/sukodublitz/PuzzleGenerator.java
> +}
Also a matter of preference I guess. I just left it with how Android Studio did it.

2019-06-19 22:03 UTC, KIsForCookie commented
The BoardGame model owns a PuzzleGenerator so I would like to merge them together. The puzzle generator is pretty simple and there's a lot of things that I am going to improve later, but it still works properly.

2019-06-23 14:17 UTC, xjchong approved these changes

2019-06-23 21:15 UTC, yufeiyang-dev approved these changes

2019-06-23 21:27 UTC, NJXZhang approved these changes

2019-06-23 22:20 UTC, merged