Feat/add buttons to game setup
best-cat-hustlers/cs446-project pull request #38
Opened 2019-06-25 22:01 UTC by NJXZhang

Add buttons to Game Setup following the prototype except shape of the radio buttons.

2019-06-25 22:22 UTC, yufeiyang-dev approved these changes

2019-06-25 22:59 UTC, KIsForCookie requested changes

2019-06-25 22:59 UTC, KIsForCookie commented on app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameBoardView.java
> -import android.view.Display;
Why are you making these changes?

2019-06-25 23:01 UTC, NJXZhang commented on app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameBoardView.java
> -import android.view.Display;
Probably I merged the wrong version. I will fix it.

2019-06-26 00:30 UTC, NJXZhang commented on app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameBoardView.java
> -import android.view.Display;
I believe the Android studio automictically removed these imports because they are not used. I don't think they need to stay in the file.

2019-06-26 00:32 UTC, KIsForCookie approved these changes

2019-06-26 00:36 UTC, merged