Pass some values fron Game Setup through intent extras
best-cat-hustlers/cs446-project pull request #77
Opened 2019-06-26 20:50 UTC by NJXZhang

Pass several variables from game setup to game Activity:
- showPoints 
- showTimer
- penaltyOn
- aiDifficulty

Not sure whether we want to save these settings or not.
Note: Some import lines are removed by Android Studio automatically because they are not being used.

2019-06-27 03:30 UTC, xjchong requested changes

2019-06-27 03:30 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivity.java
> +        intent.putExtra("aiDifficulty", aiDifficulty);
See where I've passed the model and timer info from game to results activity. I would recommend you make the keys the same way, so that they can be referred to and changed more easily.

2019-06-27 03:30 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/GameSetupActivity.java
> +        aiDifficulty = 1;
I think these simple values can be set where you declare them as class variables.

2019-06-27 03:30 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameActivity.java
> +        // TODO: Now just getting some values
I don't understand this TODO? It sounds more like an observation

2019-06-27 03:30 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/game/GameActivity.java
> +        }
Actually you don't need to add this. We are not in a rush to add it, so it should be my responsibility

2019-07-07 01:35 UTC, xjchong approved these changes

2019-07-07 17:25 UTC, yufeiyang-dev approved these changes

2019-07-07 17:25 UTC, merged