Feat/global settings
best-cat-hustlers/cs446-project pull request #80
Opened 2019-07-11 14:16 UTC by NJXZhang

Static model: MainSettingsModel
Save to SharedPreference in onDestroy() of MainSettingsActivity

2019-07-11 18:44 UTC, xjchong requested changes

2019-07-11 18:44 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/GlobalSettingsInterface.java
> +    boolean getMusic();
`boolean isSoundEnabled`
`boolean isMusicEnabled`

2019-07-11 18:44 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +class MainSettingsModel extends Observable implements GlobalSettingsInterface {
need to remove `Observable` if unused

2019-07-11 18:44 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void restoreState(SharedPreferences settings) {
When you say state, do you mean default state? Then the name should be `restoreDefaultState`

2019-07-11 18:44 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsPresenter.java
> +    private MainSettingsModel m;
Can call view `view` and model `model`, rather than `v` and `m`. Prefer to use long form for all variable names. :D

2019-07-11 18:46 UTC, yufeiyang-dev requested changes

2019-07-11 18:46 UTC, Stevenfly commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void setSound(boolean on) {
The input variable name could be `true` or `false`, consider a different name other than `on`?

2019-07-11 18:46 UTC, Stevenfly commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void setSound(boolean on) {
Also in other places in this file and `MainSettingsPresenter.java`

2019-07-11 18:53 UTC, xjchong commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void setSound(boolean on) {
For example:

```
void setIsSoundEnabled(boolean newValue) {
    _____ = newValue;
}
```

2019-07-11 20:36 UTC, NJXZhang commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void restoreState(SharedPreferences settings) {
This is the state before this activity is destroyed. Maybe I should name it savedState instead?

2019-07-12 01:13 UTC, Stevenfly commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void restoreState(SharedPreferences settings) {
`restoreLastState` or `restoreSavedState`

2019-07-12 03:34 UTC, xjchong approved these changes

2019-07-12 17:13 UTC, NJXZhang commented on app/src/main/java/com/bestCatHustlers/sukodublitz/settings/MainSettingsModel.java
> +    void restoreState(SharedPreferences settings) {
I will make changes on this settings page soon. I will change this name then.

2019-07-13 20:48 UTC, yufeiyang-dev approved these changes

2019-07-13 20:49 UTC, merged